/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Token-based color system
        ui: {
          ink: 'rgb(var(--ui-ink) / <alpha-value>)',
          text: 'rgb(var(--ui-text) / <alpha-value>)',
          muted: 'rgb(var(--ui-muted) / <alpha-value>)',
          surface: 'rgb(var(--ui-surface) / <alpha-value>)',
          card: 'rgb(var(--ui-card) / <alpha-value>)',
          border: 'rgb(var(--ui-border) / <alpha-value>)',
          divider: 'rgb(var(--ui-divider) / <alpha-value>)',
        },
        brand: {
          accent: 'rgb(var(--brand-accent) / <alpha-value>)',
          'accent-hover': 'rgb(var(--brand-accent-hover) / <alpha-value>)',
          'accent-soft': 'rgb(var(--brand-accent-soft) / <alpha-value>)',
        },
        risk: {
          'high-fg': 'rgb(var(--risk-high-fg) / <alpha-value>)',
          'high-bg': 'rgb(var(--risk-high-bg) / <alpha-value>)',
          'high-border': 'rgb(var(--risk-high-border) / <alpha-value>)',
          'medium-fg': 'rgb(var(--risk-medium-fg) / <alpha-value>)',
          'medium-bg': 'rgb(var(--risk-medium-bg) / <alpha-value>)',
          'medium-border': 'rgb(var(--risk-medium-border) / <alpha-value>)',
          'low-fg': 'rgb(var(--risk-low-fg) / <alpha-value>)',
          'low-bg': 'rgb(var(--risk-low-bg) / <alpha-value>)',
          'low-border': 'rgb(var(--risk-low-border) / <alpha-value>)',
          'info-fg': 'rgb(var(--risk-info-fg) / <alpha-value>)',
          'info-bg': 'rgb(var(--risk-info-bg) / <alpha-value>)',
          'info-border': 'rgb(var(--risk-info-border) / <alpha-value>)',
        },
        // Legacy colors (kept for gradual migration)
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
        secondary: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        neutral: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        success: {
          50: '#f0fdf4',
          100: '#dcfce7',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
        },
        warning: {
          50: '#fefce8',
          100: '#fef9c3',
          500: '#eab308',
          600: '#ca8a04',
          700: '#a16207',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
        },
      },
    },
  },
  plugins: [],
};
