export const INDUSTRY_SECTORS = [
  'Aircraft Assembly',
  'Aircraft Maintenance',
  'Aircraft Painting',
  'Aluminium',
  'Auto Assembly',
  'Auto Body',
  'Auto Paint',
  'Auto Press',
  'Chemical',
  'Data Centre',
  'Electrical Equipment Assembly',
  'Expanded Plastics',
  'Food & Beverage',
  'Foundry and Forge',
  'Glass Manufacturing',
  'Hospital',
  'Hotel',
  'Machine shops',
  'Mining',
  'Mixed use',
  'Office',
  'Other',
  'Paper',
  'Pharmaceutical',
  'Power Generation',
  'Printing',
  'Retail',
  'Residential',
  'Semiconductor',
  'Sheet Metal Working',
  'Ship Building',
  'Steel Mill',
  'Textiles',
  'Unexpanded Plastics',
  'Vacant Plants',
  'Warehouse - Ceiling sprinklers only',
  'Waste Industry',
  'Woodworking',
] as const;

export type IndustrySector = typeof INDUSTRY_SECTORS[number];
