import { supabase } from '../lib/supabase';

interface LegacyRecommendation {
  id: string;
  hazard: string;
  description: string;
  client_response?: string;
  status?: string;
  priority_override?: 'Critical' | 'High' | 'Medium' | 'Low';
  isAutoGenerated?: boolean;
}

export async function migrateSurveyRecommendations(surveyId: string): Promise<{
  success: boolean;
  migratedCount: number;
  error?: string;
}> {
  try {
    const { data: survey, error: surveyError } = await supabase
      .from('survey_reports')
      .select('form_data')
      .eq('id', surveyId)
      .single();

    if (surveyError) throw surveyError;
    if (!survey) throw new Error('Survey not found');

    const { data: existingRecs, error: existingError } = await supabase
      .from('survey_recommendations')
      .select('id')
      .eq('survey_id', surveyId);

    if (existingError) throw existingError;

    if (existingRecs && existingRecs.length > 0) {
      return {
        success: true,
        migratedCount: 0,
        error: 'Recommendations already exist for this survey'
      };
    }

    const overallComments: LegacyRecommendation[] =
      survey.form_data?.overall_comments ||
      survey.form_data?.overallComments ||
      [];

    if (overallComments.length === 0) {
      return {
        success: true,
        migratedCount: 0,
        error: 'No legacy recommendations to migrate'
      };
    }

    const priorityMap: Record<string, number> = {
      'Critical': 5,
      'High': 4,
      'Medium': 3,
      'Low': 2
    };

    const statusMap: Record<string, 'open' | 'in_progress' | 'closed' | 'deferred'> = {
      'Not Started': 'open',
      'In Progress': 'in_progress',
      'Under Review': 'in_progress',
      'Completed': 'closed',
      'Rejected': 'deferred'
    };

    const newRecommendations = overallComments
      .filter(rec => rec.hazard || rec.description)
      .map((rec, index) => ({
        survey_id: surveyId,
        template_id: null,
        title_final: rec.hazard || 'Recommendation',
        body_final: rec.description || '',
        priority: rec.priority_override ? priorityMap[rec.priority_override] || 3 : 3,
        status: rec.status ? statusMap[rec.status] || 'open' : 'open',
        owner: null,
        target_date: null,
        source: rec.isAutoGenerated ? 'triggered' as const : 'manual' as const,
        section_key: null,
        sort_index: index,
        include_in_report: true
      }));

    if (newRecommendations.length === 0) {
      return {
        success: true,
        migratedCount: 0,
        error: 'No valid recommendations to migrate'
      };
    }

    const { error: insertError } = await supabase
      .from('survey_recommendations')
      .insert(newRecommendations);

    if (insertError) throw insertError;

    return {
      success: true,
      migratedCount: newRecommendations.length
    };
  } catch (error: any) {
    console.error('Error migrating recommendations:', error);
    return {
      success: false,
      migratedCount: 0,
      error: error.message
    };
  }
}

export async function migrateAllSurveyRecommendations(): Promise<{
  success: boolean;
  totalMigrated: number;
  surveysProcessed: number;
  errors: string[];
}> {
  try {
    const { data: surveys, error: surveysError } = await supabase
      .from('survey_reports')
      .select('id');

    if (surveysError) throw surveysError;
    if (!surveys || surveys.length === 0) {
      return {
        success: true,
        totalMigrated: 0,
        surveysProcessed: 0,
        errors: []
      };
    }

    let totalMigrated = 0;
    let surveysProcessed = 0;
    const errors: string[] = [];

    for (const survey of surveys) {
      const result = await migrateSurveyRecommendations(survey.id);
      if (result.success) {
        totalMigrated += result.migratedCount;
        surveysProcessed++;
      } else if (result.error && !result.error.includes('already exist')) {
        errors.push(`${survey.id}: ${result.error}`);
      }
    }

    return {
      success: true,
      totalMigrated,
      surveysProcessed,
      errors
    };
  } catch (error: any) {
    console.error('Error in bulk migration:', error);
    return {
      success: false,
      totalMigrated: 0,
      surveysProcessed: 0,
      errors: [error.message]
    };
  }
}
