import { useState, useEffect } from 'react';
import { supabase } from '../../../lib/supabase';
import { useAuth } from '../../../contexts/AuthContext';
import FloatingSaveBar from './FloatingSaveBar';
import FeedbackModal from '../../FeedbackModal';
import ConfirmDialog from '../../ConfirmDialog';
import AddFromLibraryModal from '../../AddFromLibraryModal';
import { Plus, X, Upload, Image as ImageIcon, AlertTriangle, Filter, Table2, FileText, Library, BookmarkPlus } from 'lucide-react';

interface Document {
  id: string;
  title: string;
  assessment_date?: string;
}

interface ModuleInstance {
  id: string;
  document_id: string;
  outcome: string | null;
  assessor_notes: string;
  data: Record<string, any>;
}

interface Photo {
  path: string;
  file_name: string;
  size_bytes: number;
  mime_type: string;
  uploaded_at: string;
  previewUrl?: string; // For newly uploaded files (object URL)
}

interface Recommendation {
  id: string;
  document_id: string;
  rec_number: string;
  source_type: 'auto' | 'manual';
  library_id?: string;
  source_module_key: string;
  source_factor_key?: string;
  title: string;
  observation_text: string;
  action_required_text: string;
  hazard_text: string;
  comments_text?: string;
  status: 'Open' | 'In Progress' | 'Completed';
  priority: 'High' | 'Medium' | 'Low';
  target_date?: string;
  owner?: string;
  photos: Photo[];
  is_suppressed?: boolean;
}

interface RE09RecommendationsFormProps {
  moduleInstance: ModuleInstance;
  document: Document;
  onSaved: () => void;
}

const MAX_PHOTOS_PER_RECOMMENDATION = 3;
const MAX_PHOTO_SIZE_MB = 15;
const MAX_PHOTO_SIZE_BYTES = MAX_PHOTO_SIZE_MB * 1024 * 1024;

const MODULE_SECTIONS = [
  { key: 'RE_01_DOC_CONTROL', label: 'RE-01 Document Control' },
  { key: 'RE_02_CONSTRUCTION', label: 'RE-02 Construction' },
  { key: 'RE_03_OCCUPANCY', label: 'RE-03 Occupancy' },
  { key: 'RE_06_FIRE_PROTECTION', label: 'RE-04 Fire Protection' },
  { key: 'RE_07_NATURAL_HAZARDS', label: 'RE-05 Exposures' },
  { key: 'RE_08_UTILITIES', label: 'RE-06 Utilities' },
  { key: 'RE_09_MANAGEMENT', label: 'RE-07 Management Systems' },
  { key: 'RE_12_LOSS_VALUES', label: 'RE-08 Loss & Values' },
  { key: 'OTHER', label: 'Other' },
];

type FilterMode = 'all' | 'active' | 'completed';
type ViewMode = 'editor' | 'table';

function createEmptyRecommendation(documentId: string): Recommendation {
  return {
    id: crypto.randomUUID(),
    document_id: documentId,
    rec_number: '', // Will be auto-generated by database
    source_type: 'manual',
    source_module_key: 'OTHER',
    title: '',
    observation_text: '',
    action_required_text: '',
    hazard_text: '',
    comments_text: '',
    status: 'Open',
    priority: 'Medium',
    target_date: undefined,
    owner: '',
    photos: [],
  };
}

export default function RE09RecommendationsForm({
  moduleInstance,
  document,
  onSaved,
}: RE09RecommendationsFormProps) {
  const { profile } = useAuth();
  const [isSaving, setIsSaving] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [uploadingPhotoForRec, setUploadingPhotoForRec] = useState<string | null>(null);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [filterMode, setFilterMode] = useState<FilterMode>('all');
  const [viewMode, setViewMode] = useState<ViewMode>('editor');
  const [savingToLibrary, setSavingToLibrary] = useState<string | null>(null);
  const [photoUrls, setPhotoUrls] = useState<Record<string, string>>({});
  const [isLibraryModalOpen, setIsLibraryModalOpen] = useState(false);

  const [feedback, setFeedback] = useState<{
    isOpen: boolean;
    type: 'success' | 'error' | 'warning';
    title: string;
    message: string;
    autoClose?: boolean;
  }>({
    isOpen: false,
    type: 'success',
    title: '',
    message: '',
    autoClose: false,
  });

  const [confirmDialog, setConfirmDialog] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    onConfirm: () => void;
  }>({
    isOpen: false,
    title: '',
    message: '',
    onConfirm: () => {},
  });

  // Load recommendations from database
  useEffect(() => {
    loadRecommendations();
  }, [document.id]);

  // Load photo URLs when recommendations change
  useEffect(() => {
    loadPhotoUrls();
  }, [recommendations]);

  // Cleanup object URLs on unmount
  useEffect(() => {
    return () => {
      Object.values(photoUrls).forEach((url) => {
        if (url.startsWith('blob:')) {
          URL.revokeObjectURL(url);
        }
      });
    };
  }, []);

  const loadRecommendations = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase
        .from('re_recommendations')
        .select('*')
        .eq('document_id', document.id)
        .eq('is_suppressed', false)
        .order('rec_number', { ascending: true });

      if (error) throw error;

      setRecommendations(data || []);
    } catch (error) {
      console.error('Error loading recommendations:', error);
      setFeedback({
        isOpen: true,
        type: 'error',
        title: 'Failed to load recommendations',
        message: 'Unable to load recommendations. Please refresh the page and try again.',
        autoClose: false,
      });
    } finally {
      setIsLoading(false);
    }
  };

  const loadPhotoUrls = async () => {
    const urls: Record<string, string> = {};

    for (const rec of recommendations) {
      for (const photo of rec.photos) {
        // Skip if already have a preview URL (object URL from recent upload)
        if (photo.previewUrl) {
          urls[photo.path] = photo.previewUrl;
          continue;
        }

        // Try to get public URL from storage
        try {
          const { data } = supabase.storage
            .from('evidence')
            .getPublicUrl(photo.path);

          if (data?.publicUrl) {
            urls[photo.path] = data.publicUrl;
          }
        } catch (error) {
          console.error(`Failed to get URL for photo ${photo.path}:`, error);
        }
      }
    }

    setPhotoUrls(urls);
  };

  const addRecommendation = () => {
    const newRec = createEmptyRecommendation(document.id);
    setRecommendations([...recommendations, newRec]);
  };

  const addRecommendationFromLibrary = (libraryItem: any) => {
    const priorityToText = (priority: number): 'High' | 'Medium' | 'Low' => {
      if (priority <= 2) return 'High';
      if (priority <= 3) return 'Medium';
      return 'Low';
    };

    const newRec: Recommendation = {
      id: crypto.randomUUID(),
      document_id: document.id,
      rec_number: '', // Will be auto-generated by database
      source_type: 'manual',
      library_id: libraryItem.id,
      source_module_key: libraryItem.related_module_key || 'OTHER',
      title: libraryItem.title,
      observation_text: libraryItem.observation,
      action_required_text: libraryItem.action_required,
      hazard_text: libraryItem.hazard_risk_description,
      comments_text: libraryItem.client_response_prompt || '',
      status: 'Open',
      priority: priorityToText(libraryItem.default_priority),
      target_date: undefined,
      owner: '',
      photos: [],
    };
    setRecommendations([...recommendations, newRec]);
    setFeedback({
      isOpen: true,
      type: 'success',
      title: 'Added from library',
      message: 'Recommendation template has been added. You can now customize it for this assessment.',
      autoClose: true,
    });
  };

  const saveToLibrary = async (recId: string) => {
    setSavingToLibrary(recId);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) throw new Error('Not authenticated');

      const apiUrl = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/save-recommendation-to-library`;
      const response = await fetch(apiUrl, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${session.access_token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ recommendation_id: recId }),
      });

      const result = await response.json();

      if (!response.ok) {
        if (result.isDuplicate) {
          setFeedback({
            type: 'warning',
            message: 'This recommendation already exists in the library',
            autoClose: true,
          });
        } else {
          throw new Error(result.error || 'Failed to save to library');
        }
      } else {
        setFeedback({
          type: 'success',
          message: 'Recommendation saved to library successfully!',
          autoClose: true,
        });
      }
    } catch (error: any) {
      console.error('Error saving to library:', error);
      setFeedback({
        type: 'error',
        message: error.message || 'Failed to save recommendation to library',
        autoClose: false,
      });
    } finally {
      setSavingToLibrary(null);
    }
  };

  const removeRecommendation = (id: string) => {
    const rec = recommendations.find((r) => r.id === id);
    if (!rec) return;

    setConfirmDialog({
      isOpen: true,
      title: 'Delete recommendation',
      message: 'Are you sure you want to delete this recommendation? This action cannot be undone.',
      onConfirm: async () => {
        setConfirmDialog({ ...confirmDialog, isOpen: false });

        try {
          if (rec.rec_number) {
            if (rec.source_type === 'auto') {
              const { error } = await supabase
                .from('re_recommendations')
                .update({ is_suppressed: true })
                .eq('id', id);

              if (error) throw error;
            } else {
              const { error } = await supabase
                .from('re_recommendations')
                .delete()
                .eq('id', id);

              if (error) throw error;
            }
          }

          setRecommendations(recommendations.filter((r) => r.id !== id));

          setFeedback({
            isOpen: true,
            type: 'success',
            title: 'Recommendation deleted',
            message: 'The recommendation has been successfully removed.',
            autoClose: true,
          });
        } catch (error) {
          console.error('Error removing recommendation:', error);
          setFeedback({
            isOpen: true,
            type: 'error',
            title: 'Failed to delete recommendation',
            message: 'Unable to delete the recommendation. Please try again.',
            autoClose: false,
          });
        }
      },
    });
  };

  const updateRecommendation = (id: string, updates: Partial<Recommendation>) => {
    setRecommendations(
      recommendations.map((r) => (r.id === id ? { ...r, ...updates } : r))
    );
  };

  const handlePhotoUpload = async (recId: string, file: File) => {
    const rec = recommendations.find((r) => r.id === recId);
    if (!rec || rec.photos.length >= MAX_PHOTOS_PER_RECOMMENDATION) {
      setFeedback({
        isOpen: true,
        type: 'warning',
        title: 'Photo limit reached',
        message: `You can attach a maximum of ${MAX_PHOTOS_PER_RECOMMENDATION} photos per recommendation.`,
        autoClose: false,
      });
      return;
    }

    if (file.size > MAX_PHOTO_SIZE_BYTES) {
      const actualSize = (file.size / 1024 / 1024).toFixed(1);
      setFeedback({
        isOpen: true,
        type: 'warning',
        title: 'File too large',
        message: `Photo must be less than ${MAX_PHOTO_SIZE_MB}MB. Your file is ${actualSize}MB.`,
        autoClose: false,
      });
      return;
    }

    if (!file.type.startsWith('image/')) {
      setFeedback({
        isOpen: true,
        type: 'warning',
        title: 'Invalid file type',
        message: 'Only image files are allowed. Please select a JPG or PNG file.',
        autoClose: false,
      });
      return;
    }

    setUploadingPhotoForRec(recId);
    try {
      const fileExt = file.name.split('.').pop();
      const fileName = `${crypto.randomUUID()}.${fileExt}`;
      const filePath = `${document.id}/recommendations/${recId}/${fileName}`;

      // Create object URL for immediate preview
      const previewUrl = URL.createObjectURL(file);

      const { error: uploadError } = await supabase.storage
        .from('evidence')
        .upload(filePath, file);

      if (uploadError) throw uploadError;

      const photo: Photo = {
        path: filePath,
        file_name: file.name,
        size_bytes: file.size,
        mime_type: file.type,
        uploaded_at: new Date().toISOString(),
        previewUrl, // Include preview URL for immediate display
      };

      updateRecommendation(recId, {
        photos: [...rec.photos, photo],
      });

      // Update photoUrls state for immediate display
      setPhotoUrls((prev) => ({ ...prev, [filePath]: previewUrl }));

      setFeedback({
        isOpen: true,
        type: 'success',
        title: 'Photo uploaded',
        message: 'The photo has been successfully attached to this recommendation.',
        autoClose: true,
      });
    } catch (error) {
      console.error('Error uploading photo:', error);
      setFeedback({
        isOpen: true,
        type: 'error',
        title: 'Upload failed',
        message: 'Unable to upload the photo. Please try again.',
        autoClose: false,
      });
    } finally {
      setUploadingPhotoForRec(null);
    }
  };

  const removePhoto = (recId: string, photoPath: string) => {
    const rec = recommendations.find((r) => r.id === recId);
    if (!rec) return;

    updateRecommendation(recId, {
      photos: rec.photos.filter((p) => p.path !== photoPath),
    });
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      for (const rec of recommendations) {
        if (!rec.title.trim()) {
          setFeedback({
            isOpen: true,
            type: 'warning',
            title: 'Title required',
            message: 'All recommendations must have a title. Please add a title before saving.',
            autoClose: false,
          });
          setIsSaving(false);
          return;
        }
      }

      for (const rec of recommendations) {
        const recData = {
          id: rec.id,
          document_id: document.id,
          rec_number: rec.rec_number || undefined,
          source_type: rec.source_type,
          library_id: rec.library_id || null,
          source_module_key: rec.source_module_key,
          source_factor_key: rec.source_factor_key || null,
          title: rec.title,
          observation_text: rec.observation_text || '',
          action_required_text: rec.action_required_text || '',
          hazard_text: rec.hazard_text || '',
          comments_text: rec.comments_text || null,
          status: rec.status,
          priority: rec.priority,
          target_date: rec.target_date || null,
          owner: rec.owner || null,
          photos: rec.photos,
          is_suppressed: rec.is_suppressed || false,
          created_by: (await supabase.auth.getUser()).data.user?.id,
        };

        const { error } = await supabase
          .from('re_recommendations')
          .upsert(recData, { onConflict: 'id' });

        if (error) throw error;
      }

      await loadRecommendations();
      onSaved();

      setFeedback({
        isOpen: true,
        type: 'success',
        title: 'Saved successfully',
        message: 'All recommendations have been saved.',
        autoClose: true,
      });
    } catch (error) {
      console.error('Error saving recommendations:', error);
      setFeedback({
        isOpen: true,
        type: 'error',
        title: 'Save failed',
        message: 'Unable to save recommendations. Please try again.',
        autoClose: false,
      });
    } finally {
      setIsSaving(false);
    }
  };

  // Filter recommendations based on filter mode
  const filteredRecommendations = recommendations.filter((rec) => {
    if (filterMode === 'active') {
      return rec.status !== 'Completed';
    }
    if (filterMode === 'completed') {
      return rec.status === 'Completed';
    }
    return true;
  });

  // Generate display numbers (contiguous, UI-only, after filtering)
  const getDisplayNumber = (rec: Recommendation): string => {
    const index = filteredRecommendations.findIndex(r => r.id === rec.id);
    if (index === -1) return rec.rec_number || 'New';

    const year = document.assessment_date
      ? new Date(document.assessment_date).getFullYear()
      : new Date().getFullYear();
    const displayNum = String(index + 1).padStart(2, '0');
    return `${year}-${displayNum}`;
  };

  // Sort for report view
  const sortedForReport = [...filteredRecommendations].sort((a, b) => {
    // Active: High → Medium → Low, then target_date
    // Completed: most recent first
    if (filterMode === 'completed') {
      return new Date(b.updated_at || b.created_at).getTime() - new Date(a.updated_at || a.created_at).getTime();
    }

    // Priority order
    const priorityOrder = { High: 0, Medium: 1, Low: 2 };
    if (a.priority !== b.priority) {
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    }

    // Then by target date (earliest first)
    if (a.target_date && b.target_date) {
      return new Date(a.target_date).getTime() - new Date(b.target_date).getTime();
    }
    if (a.target_date) return -1;
    if (b.target_date) return 1;

    return 0;
  });

  const activeCount = recommendations.filter((r) => r.status !== 'Completed').length;
  const completedCount = recommendations.filter((r) => r.status === 'Completed').length;
  const autoCount = recommendations.filter((r) => r.source_type === 'auto').length;
  const manualCount = recommendations.filter((r) => r.source_type === 'manual').length;

  if (isLoading) {
    return (
      <div className="p-6 max-w-5xl mx-auto">
        <div className="text-center py-12">
          <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          <p className="mt-2 text-slate-600">Loading recommendations...</p>
        </div>
      </div>
    );
  }

  return (
    <>
      <div className="p-6 max-w-7xl mx-auto pb-24">
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-slate-900 mb-2">RE-09 — Recommendations</h2>
          <p className="text-slate-600">Risk engineering action register</p>
        </div>

        {/* Stats Banner */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <div className="flex items-start gap-3">
            <FileText className="w-5 h-5 text-blue-600 flex-shrink-0 mt-0.5" />
            <div className="flex-1">
              <p className="font-semibold text-blue-900 mb-1">Recommendations Overview</p>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-blue-800">
                <div>
                  <span className="font-semibold">{recommendations.length}</span> Total
                </div>
                <div>
                  <span className="font-semibold">{activeCount}</span> Active
                </div>
                <div>
                  <span className="font-semibold">{completedCount}</span> Completed
                </div>
                <div>
                  <span className="font-semibold">{autoCount}</span> Auto / <span className="font-semibold">{manualCount}</span> Manual
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Toolbar */}
        <div className="bg-white border border-slate-200 rounded-lg p-4 mb-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            {/* View Mode Toggle */}
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setViewMode('editor')}
                className={`px-4 py-2 text-sm font-medium rounded-lg flex items-center gap-2 ${
                  viewMode === 'editor'
                    ? 'bg-blue-600 text-white'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                <FileText className="w-4 h-4" />
                Editor
              </button>
              <button
                type="button"
                onClick={() => setViewMode('table')}
                className={`px-4 py-2 text-sm font-medium rounded-lg flex items-center gap-2 ${
                  viewMode === 'table'
                    ? 'bg-blue-600 text-white'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                <Table2 className="w-4 h-4" />
                Report Table
              </button>
            </div>

            {/* Filter Buttons */}
            <div className="flex items-center gap-2">
              <Filter className="w-4 h-4 text-slate-500" />
              <button
                type="button"
                onClick={() => setFilterMode('all')}
                className={`px-3 py-1 text-sm rounded-lg ${
                  filterMode === 'all'
                    ? 'bg-slate-800 text-white'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                All ({recommendations.length})
              </button>
              <button
                type="button"
                onClick={() => setFilterMode('active')}
                className={`px-3 py-1 text-sm rounded-lg ${
                  filterMode === 'active'
                    ? 'bg-slate-800 text-white'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                Active ({activeCount})
              </button>
              <button
                type="button"
                onClick={() => setFilterMode('completed')}
                className={`px-3 py-1 text-sm rounded-lg ${
                  filterMode === 'completed'
                    ? 'bg-slate-800 text-white'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                Completed ({completedCount})
              </button>
            </div>
          </div>
        </div>

        {/* Editor View */}
        {viewMode === 'editor' && (
          <div className="space-y-6">
            {filteredRecommendations.length === 0 && (
              <div className="bg-slate-50 border border-slate-200 rounded-lg p-8 text-center">
                <p className="text-slate-600">
                  {filterMode === 'all'
                    ? 'No recommendations yet. Add your first recommendation below.'
                    : `No ${filterMode} recommendations.`}
                </p>
              </div>
            )}

            {filteredRecommendations.map((rec) => (
              <div
                key={rec.id}
                className={`bg-white rounded-lg p-6 space-y-4 ${
                  rec.source_type === 'auto'
                    ? 'border-2 border-purple-200 shadow-sm'
                    : 'border border-slate-200'
                }`}
              >
                {/* Header */}
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-3">
                    <div>
                      <h3 className="font-semibold text-slate-900">
                        {getDisplayNumber(rec)}
                      </h3>
                      <div className="flex items-center gap-2 mt-1">
                        <span
                          className={`inline-flex items-center px-2 py-0.5 text-xs rounded-full ${
                            rec.source_type === 'auto'
                              ? 'bg-purple-100 text-purple-800'
                              : 'bg-slate-100 text-slate-700'
                          }`}
                        >
                          {rec.source_type === 'auto' ? 'AUTO' : 'MANUAL'}
                        </span>
                        <span
                          className={`inline-flex items-center px-2 py-0.5 text-xs rounded-full ${
                            rec.priority === 'High'
                              ? 'bg-red-100 text-red-800'
                              : rec.priority === 'Medium'
                              ? 'bg-amber-100 text-amber-800'
                              : 'bg-green-100 text-green-800'
                          }`}
                        >
                          {rec.priority}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {profile?.is_platform_admin && (
                      <button
                        type="button"
                        onClick={() => saveToLibrary(rec.id)}
                        disabled={savingToLibrary === rec.id}
                        className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium text-blue-700 bg-blue-50 hover:bg-blue-100 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Save this recommendation to the library for reuse"
                      >
                        <BookmarkPlus className="w-4 h-4" />
                        {savingToLibrary === rec.id ? 'Saving...' : 'Save to Library'}
                      </button>
                    )}
                    <button
                      type="button"
                      onClick={() => removeRecommendation(rec.id)}
                      className="text-red-600 hover:text-red-700 p-1"
                      title="Delete recommendation"
                    >
                      <X className="w-5 h-5" />
                    </button>
                  </div>
                </div>

                {/* Title */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    Title *
                  </label>
                  <input
                    type="text"
                    value={rec.title}
                    onChange={(e) => updateRecommendation(rec.id, { title: e.target.value })}
                    className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    placeholder="Brief title for this recommendation"
                  />
                </div>

                {/* Observation */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    Observation
                  </label>
                  <textarea
                    value={rec.observation_text}
                    onChange={(e) =>
                      updateRecommendation(rec.id, { observation_text: e.target.value })
                    }
                    rows={3}
                    className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    placeholder="What was observed during the assessment?"
                  />
                </div>

                {/* Action Required */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    Action Required
                  </label>
                  <textarea
                    value={rec.action_required_text}
                    onChange={(e) =>
                      updateRecommendation(rec.id, { action_required_text: e.target.value })
                    }
                    rows={3}
                    className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    placeholder="What action needs to be taken?"
                  />
                </div>

                {/* Hazard (highlighted) */}
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                  <div className="flex items-start gap-2 mb-2">
                    <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
                    <label className="block text-sm font-medium text-amber-900">
                      Hazard / Risk Description
                    </label>
                  </div>
                  <textarea
                    value={rec.hazard_text}
                    onChange={(e) =>
                      updateRecommendation(rec.id, { hazard_text: e.target.value })
                    }
                    rows={2}
                    className="w-full px-3 py-2 border border-amber-300 rounded-md text-sm bg-white"
                    placeholder="Describe the hazard or risk associated with this recommendation"
                  />
                </div>

                {/* Author Comments */}
                <div>
                  <label className="block text-sm font-medium text-slate-700 mb-1">
                    Author Comments (Internal Notes)
                  </label>
                  <textarea
                    value={rec.comments_text || ''}
                    onChange={(e) =>
                      updateRecommendation(rec.id, { comments_text: e.target.value })
                    }
                    rows={2}
                    className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    placeholder="Internal notes (not included in report)"
                  />
                </div>

                {/* Meta Fields */}
                <div className="grid grid-cols-2 md:grid-cols-5 gap-4 pt-4 border-t border-slate-200">
                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Priority</label>
                    <select
                      value={rec.priority}
                      onChange={(e) =>
                        updateRecommendation(rec.id, {
                          priority: e.target.value as Recommendation['priority'],
                        })
                      }
                      className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    >
                      <option value="High">High</option>
                      <option value="Medium">Medium</option>
                      <option value="Low">Low</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Status</label>
                    <select
                      value={rec.status}
                      onChange={(e) =>
                        updateRecommendation(rec.id, {
                          status: e.target.value as Recommendation['status'],
                        })
                      }
                      className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    >
                      <option value="Open">Open</option>
                      <option value="In Progress">In Progress</option>
                      <option value="Completed">Completed</option>
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Target Date
                    </label>
                    <input
                      type="date"
                      value={rec.target_date || ''}
                      onChange={(e) => updateRecommendation(rec.id, { target_date: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Owner</label>
                    <input
                      type="text"
                      value={rec.owner || ''}
                      onChange={(e) => updateRecommendation(rec.id, { owner: e.target.value })}
                      className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                      placeholder="Assigned to"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">
                      Related Module
                    </label>
                    <select
                      value={rec.source_module_key}
                      onChange={(e) =>
                        updateRecommendation(rec.id, { source_module_key: e.target.value })
                      }
                      className="w-full px-3 py-2 border border-slate-300 rounded-md text-sm"
                    >
                      {MODULE_SECTIONS.map((section) => (
                        <option key={section.key} value={section.key}>
                          {section.label}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                {/* Photos */}
                <div className="border-t border-slate-200 pt-4">
                  <div className="flex items-center justify-between mb-3">
                    <label className="block text-sm font-medium text-slate-700">
                      Supporting Photos ({rec.photos.length}/{MAX_PHOTOS_PER_RECOMMENDATION})
                    </label>
                    {rec.photos.length < MAX_PHOTOS_PER_RECOMMENDATION ? (
                      <label className="cursor-pointer inline-flex items-center gap-2 px-3 py-1.5 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700">
                        <Upload className="w-4 h-4" />
                        Add Photo
                        <input
                          type="file"
                          accept="image/jpeg,image/jpg,image/png"
                          className="hidden"
                          disabled={uploadingPhotoForRec === rec.id}
                          onChange={(e) => {
                            const file = e.target.files?.[0];
                            if (file) handlePhotoUpload(rec.id, file);
                            e.target.value = '';
                          }}
                        />
                      </label>
                    ) : (
                      <span className="text-xs text-amber-600 bg-amber-50 px-2 py-1 rounded">
                        Maximum {MAX_PHOTOS_PER_RECOMMENDATION} photos
                      </span>
                    )}
                  </div>

                  {rec.photos.length > 0 ? (
                    <div className="grid grid-cols-3 gap-4">
                      {rec.photos.map((photo) => {
                        const imageUrl = photoUrls[photo.path];
                        return (
                          <div
                            key={photo.path}
                            className="relative bg-slate-50 border border-slate-200 rounded-lg overflow-hidden"
                          >
                            <div className="aspect-video bg-slate-100 flex items-center justify-center overflow-hidden">
                              {imageUrl ? (
                                <img
                                  src={imageUrl}
                                  alt={photo.file_name}
                                  className="w-full h-full object-cover"
                                  onError={(e) => {
                                    // Fallback to placeholder if image fails to load
                                    e.currentTarget.style.display = 'none';
                                    const placeholder = e.currentTarget.nextElementSibling;
                                    if (placeholder) {
                                      (placeholder as HTMLElement).style.display = 'flex';
                                    }
                                  }}
                                />
                              ) : null}
                              <div
                                className="w-full h-full flex items-center justify-center"
                                style={{ display: imageUrl ? 'none' : 'flex' }}
                              >
                                <ImageIcon className="w-8 h-8 text-slate-400" />
                              </div>
                            </div>
                            <button
                              type="button"
                              onClick={() => removePhoto(rec.id, photo.path)}
                              className="absolute top-2 right-2 p-1 bg-red-600 text-white rounded-full hover:bg-red-700 shadow-md"
                            >
                              <X className="w-4 h-4" />
                            </button>
                            <div className="p-2 text-xs text-slate-600">
                              <p className="truncate" title={photo.file_name}>{photo.file_name}</p>
                              <p className="text-slate-500">{(photo.size_bytes / 1024 / 1024).toFixed(1)} MB</p>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  ) : (
                    <div className="text-center py-6 bg-slate-50 border border-dashed border-slate-300 rounded-lg text-sm text-slate-500">
                      No photos attached (max {MAX_PHOTO_SIZE_MB}MB per photo)
                    </div>
                  )}

                  {uploadingPhotoForRec === rec.id && (
                    <div className="text-sm text-blue-600 mt-2">Uploading photo...</div>
                  )}
                </div>
              </div>
            ))}

            <div className="grid grid-cols-2 gap-4">
              <button
                type="button"
                onClick={() => setIsLibraryModalOpen(true)}
                className="py-3 border-2 border-dashed border-blue-300 rounded-lg text-blue-600 hover:border-blue-500 hover:bg-blue-50 flex items-center justify-center gap-2 font-medium"
              >
                <Library className="w-5 h-5" />
                Add from Library
              </button>
              <button
                type="button"
                onClick={addRecommendation}
                className="py-3 border-2 border-dashed border-slate-300 rounded-lg text-slate-600 hover:border-slate-500 hover:bg-slate-50 flex items-center justify-center gap-2"
              >
                <Plus className="w-5 h-5" />
                Add Manual Recommendation
              </button>
            </div>
          </div>
        )}

        {/* Table View */}
        {viewMode === 'table' && (
          <div className="space-y-6">
            {/* Active Recommendations Table */}
            {(filterMode === 'all' || filterMode === 'active') && (
              <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
                <div className="bg-slate-50 px-6 py-3 border-b border-slate-200">
                  <h3 className="font-semibold text-slate-900">
                    Active Recommendations ({activeCount})
                  </h3>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-50 border-b border-slate-200">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Ref
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Title
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Priority
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Status
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Target
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Module
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Owner
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {sortedForReport
                        .filter((r) => r.status !== 'Completed')
                        .map((rec) => (
                          <tr key={rec.id} className="hover:bg-slate-50">
                            <td className="px-4 py-3 font-mono text-xs">{getDisplayNumber(rec)}</td>
                            <td className="px-4 py-3">{rec.title}</td>
                            <td className="px-4 py-3">
                              <span
                                className={`inline-flex px-2 py-1 text-xs rounded-full ${
                                  rec.priority === 'High'
                                    ? 'bg-red-100 text-red-800'
                                    : rec.priority === 'Medium'
                                    ? 'bg-amber-100 text-amber-800'
                                    : 'bg-green-100 text-green-800'
                                }`}
                              >
                                {rec.priority}
                              </span>
                            </td>
                            <td className="px-4 py-3">{rec.status}</td>
                            <td className="px-4 py-3">
                              {rec.target_date
                                ? new Date(rec.target_date).toLocaleDateString()
                                : '—'}
                            </td>
                            <td className="px-4 py-3 text-xs text-slate-600">
                              {MODULE_SECTIONS.find((m) => m.key === rec.source_module_key)
                                ?.label || rec.source_module_key}
                            </td>
                            <td className="px-4 py-3">{rec.owner || '—'}</td>
                          </tr>
                        ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Completed Recommendations Table */}
            {(filterMode === 'all' || filterMode === 'completed') && (
              <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
                <div className="bg-green-50 px-6 py-3 border-b border-green-200">
                  <h3 className="font-semibold text-green-900">
                    Completed Recommendations ({completedCount})
                  </h3>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-sm">
                    <thead className="bg-slate-50 border-b border-slate-200">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Ref
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Title
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Priority
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Module
                        </th>
                        <th className="px-4 py-3 text-left text-xs font-semibold text-slate-600">
                          Owner
                        </th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100">
                      {sortedForReport
                        .filter((r) => r.status === 'Completed')
                        .map((rec) => (
                          <tr key={rec.id} className="hover:bg-slate-50">
                            <td className="px-4 py-3 font-mono text-xs">{getDisplayNumber(rec)}</td>
                            <td className="px-4 py-3">{rec.title}</td>
                            <td className="px-4 py-3">
                              <span
                                className={`inline-flex px-2 py-1 text-xs rounded-full ${
                                  rec.priority === 'High'
                                    ? 'bg-red-100 text-red-800'
                                    : rec.priority === 'Medium'
                                    ? 'bg-amber-100 text-amber-800'
                                    : 'bg-green-100 text-green-800'
                                }`}
                              >
                                {rec.priority}
                              </span>
                            </td>
                            <td className="px-4 py-3 text-xs text-slate-600">
                              {MODULE_SECTIONS.find((m) => m.key === rec.source_module_key)
                                ?.label || rec.source_module_key}
                            </td>
                            <td className="px-4 py-3">{rec.owner || '—'}</td>
                          </tr>
                        ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <FloatingSaveBar onSave={handleSave} isSaving={isSaving} />

      <FeedbackModal
        isOpen={feedback.isOpen}
        onClose={() => setFeedback({ ...feedback, isOpen: false })}
        type={feedback.type}
        title={feedback.title}
        message={feedback.message}
        autoClose={feedback.autoClose}
      />

      <ConfirmDialog
        isOpen={confirmDialog.isOpen}
        onConfirm={confirmDialog.onConfirm}
        onCancel={() => setConfirmDialog({ ...confirmDialog, isOpen: false })}
        title={confirmDialog.title}
        message={confirmDialog.message}
        confirmText="Delete"
        cancelText="Cancel"
        type="danger"
      />

      <AddFromLibraryModal
        isOpen={isLibraryModalOpen}
        onClose={() => setIsLibraryModalOpen(false)}
        onSelect={addRecommendationFromLibrary}
      />
    </>
  );
}
